TASK: TRAIN_SENTIMENT_MODEL

TRAINING:
    LEARNING_RATE: 0.0001
    EPOCH: 20
    DEVICE: cuda
    BATCH_SIZE: 32
    WARMUP: 1738
    PATIENCE: 5
    SCORE: [sentiment_mse, empathy_mse]
    CHECKPOINT_PATH: /content/drive/MyDrive/demo1/checkpoints/EmpathySent/checkpoints_0
    DATA_PATH:
        TRAIN: /content/drive/MyDrive/demo1/training_data/empaSent/train.csv
        DEV:   /content/drive/MyDrive/demo1/training_data/empaSent/dev.csv
        TEST:  /content/drive/MyDrive/demo1/training_data/empaSent/test.csv

MODEL:
    PRETRAINED: tabularisai/multilingual-sentiment-analysis
    IN_FEATURE: 768
    DIM: 768
    EMPATHY: 1
    SENTIMENT: 1
    DROPOUT: 0.2
    FREEZE_BACKBONE: False

DATA:
    PRETRAINED: tabularisai/multilingual-sentiment-analysis
    NUM_ITEMS: 25402
    DATA_PATH:
        TRAIN: /content/drive/MyDrive/demo1/training_data/empaSent/train.csv
        DEV:   /content/drive/MyDrive/demo1/training_data/empaSent/dev.csv
        TEST:  /content/drive/MyDrive/demo1/training_data/empaSent/test.csv
