

TASK: TRAIN_MODEL

TRAINING:
    LEARNING_RATE: 0.0001
    EPOCH: 100
    DEVICE: cpu
    SCORE: accuracy
    BATCH_SIZE: 32
    WARMUP: 200
    PATIENCE: 5
    CHECKPOINT_PATH: saved_models
    TOXIC_WEIGHTED_LOSS: [1.3597, 3.780]
    DATA_PATH:
        TRAIN: /content/drive/MyDrive/demo1/training_data/train.csv
        DEV:   /content/drive/MyDrive/demo1/training_data/dev.csv
        TEST:  /content/drive/MyDrive/demo1/training_data/test.csv

MODEL:
    IN_FEATURE: 768
    DIM: 768
    ANGER: 2
    TOXICITY: 2
    DROPOUT: 0.2
    FREEZE_BACKBONE: False

DATA:
    NUM_ITEMS: 25402
    IMAGE_FOLDER: data/images
    DATA_PATH:
        TRAIN: /content/drive/MyDrive/demo1/training_data/train.csv
        DEV:   /content/drive/MyDrive/demo1/training_data/dev.csv
        TEST:  /content/drive/MyDrive/demo1/training_data/test.csv
